### ISSUE TITLE
Populating the bids information on the rules file from different sources

### ISSUE THREAD

**Issue by yjmantilla** [yjmantilla/sovabids#24]
I have been meditating about how bidscoin and sovabids work and one of the ideas is collecting information from the files (bidscoin does it from the DICOM header) and returning that information as "attributes". Then one populates the bids information with those attributes collected. See the following example:

```yaml

  subject: <<entities.subject>>
  session: <<entities.session>>

    attributes:
      sidecar:
      channels.name:
      channels.type:
      channels.units:
      entities.subject:
      entities.task:
      entities.session:
      entities.run:
      dataset_description:
    bids:
      task: <<entities.task>>
      acq: 
      run: <<entities.run>>       
      suffix: eeg
```

In our case I mainly extract information from the path since usually (correct me if im wrong) the headers of eeg files do not contain such information. In any case If we generalize the idea from extracting information from a given source then we could implement something like this:

```yaml
heuristics :
  path:
    pattern: some regex pattern
    fields: 
      - task
      - subject
      - session
  from_tabular1:
    file: some csv file for example
    split: ,
  from_dictionary1:
    file: some json or yaml file #extracts as a dictionary
  from_tabular2:
    file: some tsv file
    split: \t

entities :
  session : <path.session> 
  task : <path.task>
  acquisition : 
  run : 
  subject: <path.subject>

electrodes :
  - name : <from_tabular1.somerow.somecolumn>
    x : <from_tabular2.somerow.somecolumn> + <from_tabular2.somerow.somecolumn> #include basic operations?

channels:
  - name : <from_tabular1.somerow.somecolumn>

sidecar:
  PowerLineFrequency : <from_dictionary1.line_freq>

```

The idea of extracting info from arbitrary files can be seen in @civier original configuration file proposal:

### General configuration file format

Example of one row in the table:

| Origin location                                                                 | Target location                                                                                   | Formula     |
|---------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------|-------------|
| subject1/eeg/session${A}/config.csv/1/8 subject1/eeg/session${A}/config.csv/1/9 | eeg/eeg_rest_raw/sub-1/ses-rest-ses${A}/eeg/sub-1_ses-rest_coordsystem.json/“Coordinates”/“NAS”/2 | ${1} + ${2} |

So I was wondering if this what something worth exploring for the community. @civier
